#!/usr/bin/env bash
# Renders the six art assets the Discord application needs, from Paseo's own artwork.
#
# Usage: scripts/render-assets.sh [path-to-paseo-checkout]
#
# The large image is Paseo's app icon. The small images are the status dots Paseo draws beside its own
# workspace rows, in Paseo's colours, as bare circles: Discord renders the small image at about 20px, where
# a whole icon with a dot on it is unreadable.
#
# Source: https://github.com/getpaseo/paseo, Apache-2.0, packages/app/assets/images.
set -euo pipefail

PASEO_DIR="${1:-$HOME/Programming/misc/paseo}"
IMAGES="$PASEO_DIR/packages/app/assets/images"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/assets"

if [ ! -d "$IMAGES" ]; then
  echo "Paseo artwork not found at $IMAGES" >&2
  echo "Pass the path to a Paseo checkout: scripts/render-assets.sh /path/to/paseo" >&2
  exit 1
fi

for tool in magick rsvg-convert; do
  command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
done

mkdir -p "$OUT"

# Discord requires art assets to be at least 512x512.
magick "$IMAGES/icon.png" -resize 512x512 -colorspace sRGB -type TrueColor "$OUT/paseo.png"

dot() {
  local name="$1" colour="$2"
  rsvg-convert -w 512 -h 512 -o "$OUT/$name.png" /dev/stdin <<SVG
<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <circle cx="256" cy="256" r="256" fill="$colour"/>
</svg>
SVG
}

# Paseo's own status dot colours, dark theme, from packages/app/src/styles/theme.ts.
# Its favicon collapses needs_input and attention into one green; the sidebar does not, and neither
# does this: being asked for a permission is not the same as being handed the turn back.
dot needs_input "#db932e"
dot failed "#f7796d"
dot running "#5caaf6"
dot attention "#35c264"
# Paseo draws no dot at all for a finished workspace, so grey is this plugin's own.
dot idle "#6b7280"

# The settings panel previews the same large image, and a plugin bundle cannot read this directory at
# runtime, so the icon is inlined into the client as a data URL.
ARTWORK="$ROOT/client/artwork.ts"
magick "$OUT/paseo.png" -resize 96x96 -strip "$OUT/.paseo-preview.png"
{
  echo "// Generated by scripts/render-assets.sh from assets/paseo.png."
  echo "// The preview draws the large image Discord shows, and a plugin bundle cannot read the assets directory at runtime."
  echo
  printf 'export const PASEO_ICON_DATA_URL =\n  "data:image/png;base64,%s";\n' "$(base64 -w0 "$OUT/.paseo-preview.png")"
} > "$ARTWORK"
rm "$OUT/.paseo-preview.png"

echo "Wrote:"
ls -1 "$OUT"
echo "client/artwork.ts"
